name: test coverage

on: [push]

jobs:
  check:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc, rust-std, cargo, llvm-tools, llvm-tools-preview
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: grcov
      - uses: Swatinem/rust-cache@v2
      - name: Run profiling tests
        run: |
          mkdir -p target/debug/coverage
          cargo test --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Cinstrument-coverage -Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Cinstrument-coverage -Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Z unstable-options --persist-doctests target/debug'

      - name: Run grcov
        id: coverage
        run: grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/debug/coverage/

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/debug/coverage/lcov
